### ISSUE TITLE
About boundary-iou

### ISSUE THREAD

**Issue by JohannesTheo** [kdexd/coco-rem#3]
Hey @kdexd, 

great effort and congrats on the ECCV paper! 🥳  I'm already using the annotations in my work :)

I was wondering if you will also report boundary-iou in the upcoming ECCV paper? I'v seen that you are calculating it in the evaluator but the arXiv version 'only' reports mask AP if I'm not mistaken?

Either way, great work!

**Comment by ydvaayan** [comment]
Hey @JohannesTheo,

Thanks for taking interest in our work!
We do add boundary AP for a bunch of models in appendix of ECCV version to illustrate boundary refinement. tl;dr Boundary AP scores improve across various models.

**Comment by kdexd** [comment]
Added boundary IoU support in the code release, cheers!

**Comment by JohannesTheo** [comment]
Hey @ydvaayan 

Thanks! Looking forward to the final paper :) It's nice to have this confirmed. I've seen so many mask predicitons where the prediction is arguably better then the label and I was alywas wondering how scores would change with better annotations.
